"""aggiunto anno percorso nelle iscrizioni

Revision ID: 2cc4384ffa62
Revises: 52aec5b28f88
Create Date: 2026-06-02 13:43:14.601009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc4384ffa62'
down_revision = '52aec5b28f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iscrizioni_eg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anno_percorso', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_iscrizioni_eg_status_percorso_id', 'status_percorso', ['anno_percorso'], ['id'])

    op.drop_constraint(
        '1',
        'iscrizioni_eg',
        type_='foreignkey'
    )

    op.create_foreign_key(
        'fk_iscrizioni_eg_gruppi_id',
        'iscrizioni_eg',
        'gruppi',
        ['gruppo'],
        ['id']
    )

    op.drop_constraint(
        '2',
        'iscrizioni_eg',
        type_='foreignkey'
    )

    op.create_foreign_key(
        'fk_iscrizioni_eg_zone_id',
        'iscrizioni_eg',
        'zone',
        ['zona'],
        ['id']
    )

    op.create_foreign_key(
        'fk_iscrizioni_eg_regioni_id',
        'iscrizioni_eg',
        'regioni',
        ['regione'],
        ['id']
    )

    op.drop_constraint(
        '2',
        'wordpress_post',
        type_='foreignkey'
    )

    op.create_foreign_key(
        'fk_wordpress_post_wordpress_user_id',
        'wordpress_post',
        'wordpress_user',
        ['wordpress_user_id'],
        ['id']
    )

    op.drop_constraint(
        '1',
        'user',
        type_='foreignkey'
    )

    op.create_foreign_key(
        'fk_user_regioni_id',
        'user',
        'regioni',
        ['regione'],
        ['id']
    )

    op.drop_constraint(
        '2',
        'user',
        type_='foreignkey'
    )

    op.create_foreign_key(
        'fk_user_zone_id',
        'user',
        'zone',
        ['zona'],
        ['id']
    )

    op.drop_constraint(
        '1',
        'mail_massive',
        type_='foreignkey'
    )

    op.create_foreign_key(
        'fk_mail_massive_regioni_id',
        'mail_massive',
        'regioni',
        ['regione'],
        ['id']
    )

    op.drop_constraint(
        '1',
        'coda_mail',
        type_='foreignkey'
    )

    op.create_foreign_key(
        'fk_coda_mail_regioni_id',
        'coda_mail',
        'regioni',
        ['regione'],
        ['id']
    )

    op.drop_constraint(
        '1',
        'status_percorso',
        type_='foreignkey'
    )

    op.create_foreign_key(
        'fk_status_percorso_regioni_id',
        'status_percorso',
        'regioni',
        ['regione'],
        ['id']
    )

    op.drop_constraint(
        '1',
        'zone',
        type_='foreignkey'
    )

    op.create_foreign_key(
        'fk_zone_regioni_id',
        'zone',
        'regioni',
        ['regione'],
        ['id']
    )

    op.drop_constraint(
        '1',
        'gruppi',
        type_='foreignkey'
    )

    op.create_foreign_key(
        'fk_gruppi_regioni_id',
        'gruppi',
        'regioni',
        ['regione'],
        ['id']
    )

    op.drop_constraint(
        '2',
        'gruppi',
        type_='foreignkey'
    )

    op.create_foreign_key(
        'fk_gruppi_zone_id',
        'gruppi',
        'zone',
        ['zona'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iscrizioni_eg', schema=None) as batch_op:
        batch_op.drop_constraint('fk_iscrizioni_eg_status_percorso_id', type_='foreignkey')
        batch_op.drop_column('anno_percorso')

    op.drop_constraint(
        'fk_iscrizioni_eg_gruppi_id',
        'iscrizioni_eg',
        type_='foreignkey'
    )

    op.create_foreign_key(
        '1',
        'iscrizioni_eg',
        'gruppi',
        ['gruppo'],
        ['id']
    )

    op.drop_constraint(
        'fk_iscrizioni_eg_zone_id',
        'iscrizioni_eg',
        type_='foreignkey'
    )

    op.create_foreign_key(
        '2',
        'iscrizioni_eg',
        'zone',
        ['zona'],
        ['id']
    )

    op.drop_constraint(
        'fk_iscrizioni_eg_regioni_id',
        'iscrizioni_eg',
        type_='foreignkey'
    )

    op.drop_constraint(
        'fk_wordpress_post_wordpress_user_id',
        'wordpress_post',
        type_='foreignkey'
    )

    op.create_foreign_key(
        '2',
        'wordpress_post',
        'wordpress_user',
        ['wordpress_user_id'],
        ['id']
    )

    op.drop_constraint(
        'fk_user_regioni_id',
        'user',
        type_='foreignkey'
    )

    op.create_foreign_key(
        '1',
        'user',
        'regioni',
        ['regione'],
        ['id']
    )

    op.drop_constraint(
        'fk_user_zone_id',
        'user',
        type_='foreignkey'
    )

    op.create_foreign_key(
        '2',
        'user',
        'zone',
        ['zona'],
        ['id']
    )


    op.drop_constraint(
        'fk_mail_massive_regioni_id',
        'mail_massive',
        type_='foreignkey'
    )

    op.create_foreign_key(
        '1',
        'mail_massive',
        'regioni',
        ['regione'],
        ['id']
    )

    op.drop_constraint(
        'fk_coda_mail_regioni_id',
        'coda_mail',
        type_='foreignkey'
    )

    op.create_foreign_key(
        '1',
        'coda_mail',
        'regioni',
        ['regione'],
        ['id']
    )

    op.drop_constraint(
        'fk_status_percorso_regioni_id',
        'status_percorso',
        type_='foreignkey'
    )

    op.create_foreign_key(
        '1',
        'status_percorso',
        'regioni',
        ['regione'],
        ['id']
    )

    op.drop_constraint(
        'fk_zone_regioni_id',
        'zone',
        type_='foreignkey'
    )

    op.create_foreign_key(
        '1',
        'zone',
        'regioni',
        ['regione'],
        ['id']
    )

    op.drop_constraint(
        'fk_gruppi_regioni_id',
        'gruppi',
        type_='foreignkey'
    )

    op.create_foreign_key(
        '1',
        'gruppi',
        'regioni',
        ['regione'],
        ['id']
    )

    op.drop_constraint(
        'fk_gruppi_zone_id',
        'gruppi',
        type_='foreignkey'
    )

    op.create_foreign_key(
        '2',
        'gruppi',
        'zone',
        ['zona'],
        ['id']
    )
    # ### end Alembic commands ###
