"""aggiunto anno percorso nelle iscrizioni

Revision ID: 2cc4384ffa62
Revises: 52aec5b28f88
Create Date: 2026-06-02 13:43:14.601009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc4384ffa62'
down_revision = '52aec5b28f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iscrizioni_eg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anno_percorso', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_iscrizioni_eg_status_percorso_id', 'status_percorso', ['anno_percorso'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iscrizioni_eg', schema=None) as batch_op:
        batch_op.drop_constraint('fk_iscrizioni_eg_status_percorso_id', type_='foreignkey')
        batch_op.drop_column('anno_percorso')
    # ### end Alembic commands ###
