"""rimossa AnnoCorrente e creata SysOption

Revision ID: 3ce459f44cee
Revises: b06b215b6e70
Create Date: 2026-05-21 14:46:24.413509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ce459f44cee'
down_revision = 'b06b215b6e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_option',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    conn = op.get_bind()

    result = conn.execute(
        text("SELECT value FROM anno_corrente LIMIT 1")
    ).fetchone()

    if result is not None:
        conn.execute(
            text("""
                INSERT INTO system_option (`key`, `value`)
                VALUES (:key, :value)
            """),
            {
                "key": "AnnoCorrente",
                "value": result[0]
            }
        )

    op.drop_table('anno_corrente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anno_corrente',
    sa.Column('value', mysql.VARCHAR(length=4), nullable=False),
    sa.PrimaryKeyConstraint('value'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    conn = op.get_bind()

    result = conn.execute(
        text("""
            SELECT value
            FROM system_option
            WHERE `key` = 'AnnoCorrente'
            LIMIT 1
        """)
    ).fetchone()

    if result is not None:
        conn.execute(
            text("""
                INSERT INTO anno_corrente (value)
                VALUES (:value)
            """),
            {
                "value": result[0]
            }
        )

    op.drop_table('system_option')
    # ### end Alembic commands ###
