"""stato rel puglia booleano

Revision ID: 42b33e98a7ee
Revises: 2cc4384ffa62
Create Date: 2026-06-02 17:23:06.405945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42b33e98a7ee'
down_revision = '2cc4384ffa62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relazioni_puglia', schema=None) as batch_op:
        batch_op.alter_column('stato',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.Boolean(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relazioni_puglia', schema=None) as batch_op:
        batch_op.alter_column('stato',
               existing_type=sa.Boolean(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=False)

    # ### end Alembic commands ###
