"""aggiunta mail massiva e spostata creazione demoni in db

Revision ID: 52aec5b28f88
Revises: 3ce459f44cee
Create Date: 2026-06-02 12:03:06.301825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
from sqlalchemy.dialects import mysql
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '52aec5b28f88'
down_revision = '3ce459f44cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_massive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('stato', sa.String(length=255), nullable=False),
    sa.Column('regione', sa.Integer(), nullable=False),
    sa.Column('destinatari', sa.JSON(), nullable=False),
    sa.Column('titolo', sa.String(length=255), nullable=False),
    sa.Column('testo', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['regione'], ['regioni.id'], name='fk_mail_massive_regioni_id'),
    sa.PrimaryKeyConstraint('id')
    )

    conn = op.get_bind()
    conn.execute(text("TRUNCATE TABLE demoni"))
    conn.execute(text("INSERT INTO demoni (`key`, `value`) VALUES (:key, :value)"),
            {
                "key": "send_notifiche",
                "value": True
            })
    conn.execute(text("INSERT INTO demoni (`key`, `value`) VALUES (:key, :value)"),
            {
                "key": "send_mail",
                "value": True
            })
    conn.execute(text("INSERT INTO demoni (`key`, `value`) VALUES (:key, :value)"),
            {
                "key": "send_telegram",
                "value": True
            })
    conn.execute(text("INSERT INTO demoni (`key`, `value`) VALUES (:key, :value)"),
            {
                "key": "job_wordpress",
                "value": True
            })

    result_anno_corrente = conn.execute(
        text("""
            SELECT value
            FROM system_option
            WHERE `key` = 'AnnoCorrente'
            LIMIT 1
        """)
    ).fetchone()

    result_template_post = conn.execute(
        text("""
            SELECT value
            FROM system_option
            WHERE `key` = 'TemplatePost'
            LIMIT 1
        """)
    ).fetchone()

    conn.execute(text("TRUNCATE TABLE system_option;"))

    if result_anno_corrente is not None:
        conn.execute(
            text("""
                INSERT INTO system_option (`key`, `value`)
                VALUES (:key, :value)
            """),
            {
                "key": "AnnoCorrente",
                "value": result_anno_corrente[0]
            }
        )
    else:
        conn.execute(
            text("""
                INSERT INTO system_option (`key`, `value`)
                VALUES (:key, :value)
            """),
            {
                "key": "AnnoCorrente",
                "value": str(datetime.today().year)
            }
        )

    if result_template_post is not None:
        conn.execute(
            text("""
                INSERT INTO system_option (`key`, `value`)
                VALUES (:key, :value)
            """),
            {
                "key": "TemplatePost",
                "value": result_template_post[0]
            }
        )
    else:
        conn.execute(
            text("""
                INSERT INTO system_option (`key`, `value`)
                VALUES (:key, :value)
            """),
            {
                "key": "TemplatePost",
                "value": "8183"
            }
        )

    op.rename_table('iscrizioniEG', 'iscrizioni_eg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail_massive')

    conn = op.get_bind()
    conn.execute(text("TRUNCATE TABLE demoni;"))

    op.rename_table('iscrizioni_eg', 'iscrizioniEG')
    # ### end Alembic commands ###
