"""aggiunta coda telegram

Revision ID: b06b215b6e70
Revises: d8674f5026a8
Create Date: 2026-05-01 20:26:17.688569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06b215b6e70'
down_revision = 'd8674f5026a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coda_telegram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('stato', sa.String(length=255), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(length=255), nullable=False),
    sa.Column('testo', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coda_telegram')
    # ### end Alembic commands ###
