"""init schema

Revision ID: d8674f5026a8
Revises: 
Create Date: 2026-04-24 14:36:22.615457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8674f5026a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anno_corrente',
    sa.Column('value', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('value')
    )
    op.create_table('demoni',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('job_wordpress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('stato', sa.String(length=255), nullable=False),
    sa.Column('dati', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regione', sa.String(length=255), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coda_mail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('stato', sa.String(length=255), nullable=False),
    sa.Column('regione', sa.Integer(), nullable=False),
    sa.Column('indirizzi', sa.JSON(), nullable=False),
    sa.Column('indirizzi_copia', sa.JSON(), nullable=False),
    sa.Column('titolo', sa.String(length=255), nullable=False),
    sa.Column('testo', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['regione'], ['regioni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_percorso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anno', sa.String(length=4), nullable=True),
    sa.Column('iscrizioni', sa.JSON(), nullable=False),
    sa.Column('abilitazioni', sa.JSON(), nullable=False),
    sa.Column('regione', sa.Integer(), nullable=True),
    sa.Column('data_apertura', sa.DateTime(), nullable=True),
    sa.Column('data_chiusura', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['regione'], ['regioni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zona', sa.String(length=255), nullable=False),
    sa.Column('regione', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['regione'], ['regioni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gruppi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gruppo', sa.String(length=255), nullable=True),
    sa.Column('zona', sa.Integer(), nullable=False),
    sa.Column('regione', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['regione'], ['regioni.id'], ),
    sa.ForeignKeyConstraint(['zona'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=False),
    sa.Column('regione', sa.Integer(), nullable=True),
    sa.Column('zona', sa.Integer(), nullable=True),
    sa.Column('livello', sa.String(length=255), nullable=False),
    sa.Column('telegram_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['regione'], ['regioni.id'], ),
    sa.ForeignKeyConstraint(['zona'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('iscrizioniEG',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('stato', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=False),
    sa.Column('regione', sa.Integer(), nullable=False),
    sa.Column('zona', sa.Integer(), nullable=False),
    sa.Column('gruppo', sa.Integer(), nullable=False),
    sa.Column('specialita', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('nome_capo_sq', sa.String(length=255), nullable=False),
    sa.Column('nome_capo1', sa.String(length=255), nullable=False),
    sa.Column('mail_capo1', sa.String(length=255), nullable=False),
    sa.Column('cell_capo1', sa.String(length=255), nullable=False),
    sa.Column('nome_capo2', sa.String(length=255), nullable=False),
    sa.Column('mail_capo2', sa.String(length=255), nullable=False),
    sa.Column('cell_capo2', sa.String(length=255), nullable=False),
    sa.Column('sesso', sa.String(length=2), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['gruppo'], ['gruppi.id'], ),
    sa.ForeignKeyConstraint(['zona'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relazioni_puglia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('stato', sa.JSON(), nullable=False),
    sa.Column('iscrizioni_id', sa.Integer(), nullable=False),
    sa.Column('dati', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['iscrizioni_id'], ['iscrizioniEG.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wordpress_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('iscrizioni_id', sa.Integer(), nullable=False),
    sa.Column('wordpress_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['iscrizioni_id'], ['iscrizioniEG.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wordpress_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('iscrizioni_id', sa.Integer(), nullable=False),
    sa.Column('wordpress_user_id', sa.Integer(), nullable=False),
    sa.Column('wordpress_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['iscrizioni_id'], ['iscrizioniEG.id'], ),
    sa.ForeignKeyConstraint(['wordpress_user_id'], ['wordpress_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wordpress_post')
    op.drop_table('wordpress_user')
    op.drop_table('relazioni_puglia')
    op.drop_table('iscrizioniEG')
    op.drop_table('user')
    op.drop_table('gruppi')
    op.drop_table('zone')
    op.drop_table('status_percorso')
    op.drop_table('coda_mail')
    op.drop_table('regioni')
    op.drop_table('job_wordpress')
    op.drop_table('demoni')
    op.drop_table('anno_corrente')
    # ### end Alembic commands ###
