name: Build Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Gestionale Image
      working-directory: gestionale
      run: |
        docker build . \
          --file Dockerfile \
          --tag ghcr.io/egit-guidoncini-verdi/guidonciniverdi-gestionale:${{ github.sha }} \
          --tag ghcr.io/egit-guidoncini-verdi/guidonciniverdi-gestionale:latest

    - name: Push Gestionale Image
      run: |
        docker push ghcr.io/egit-guidoncini-verdi/guidonciniverdi-gestionale:${{ github.sha }}
        docker push ghcr.io/egit-guidoncini-verdi/guidonciniverdi-gestionale:latest

    - name: Build Notifiche Image
      working-directory: worker-notifiche
      run: |
        docker build . \
          --file Dockerfile \
          --tag ghcr.io/egit-guidoncini-verdi/guidonciniverdi-worker-notifiche:${{ github.sha }} \
          --tag ghcr.io/egit-guidoncini-verdi/guidonciniverdi-worker-notifiche:latest

    - name: Push Notifiche Image
      run: |
        docker push ghcr.io/egit-guidoncini-verdi/guidonciniverdi-worker-notifiche:${{ github.sha }}
        docker push ghcr.io/egit-guidoncini-verdi/guidonciniverdi-worker-notifiche:latest