name: Build Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-gestionale:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Gestionale Image
      working-directory: gestionale
      run: |
        docker build . \
          --file Dockerfile \
          --tag ghcr.io/egit-guidoncini-verdi/guidonciniverdi-gestionale:${{ github.sha }} \
          --tag ghcr.io/egit-guidoncini-verdi/guidonciniverdi-gestionale:latest

    - name: Push Gestionale Image
      run: |
        docker push ghcr.io/egit-guidoncini-verdi/guidonciniverdi-gestionale:${{ github.sha }}
        docker push ghcr.io/egit-guidoncini-verdi/guidonciniverdi-gestionale:latest

  build-deamon:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
    - name: Build Gestionale Deamon Image
      working-directory: gestionale-deamon
      run: |
        docker build . \
          --file Dockerfile \
          --tag ghcr.io/egit-guidoncini-verdi/guidonciniverdi-gestionale-deamon:${{ github.sha }} \
          --tag ghcr.io/egit-guidoncini-verdi/guidonciniverdi-gestionale-deamon:latest

    - name: Push Gestionale Deamon Image
      run: |
        docker push ghcr.io/egit-guidoncini-verdi/guidonciniverdi-gestionale-deamon:${{ github.sha }}
        docker push ghcr.io/egit-guidoncini-verdi/guidonciniverdi-gestionale-deamon:latest